### ISSUE TITLE
目前接口是以form表单形式上传的，能否支持选择以JSON-SCHEMA或者json5方式上传呢

### ISSUE THREAD

**Issue by jennyjane** [Forgus/api-generator#11]
目前接口是以form表单形式上传的，能否支持选择以JSON-SCHEMA或者json5方式上传呢
目前的格式：
![image](https://user-images.githubusercontent.com/19267219/80282217-d2a76b00-8742-11ea-8e45-691a26a5dda1.png)

期望-JSON-SCHEMA格式：
![image](https://user-images.githubusercontent.com/19267219/80282199-b5729c80-8742-11ea-9880-d9c3feab67f9.png)

期望-json5格式：
![image](https://user-images.githubusercontent.com/19267219/80282179-983dce00-8742-11ea-9aca-fb55735ebf17.png)

**Comment by Forgus** [comment]
如果你的接口定义的数据传输格式是json（包含RequestBody或ResponseBody注解），那么生成的yapi文档默认是json5格式的，建议你可以检查下自己的接口定义。如果还有问题可以把相关接口定义和出入参的结构截个图发我邮箱（wenbin1876@gmail.com），我帮你分析下。
