### ISSUE TITLE
@RestController 写了value值就报Invalid Class File!不填就可以上传

### ISSUE THREAD

**Issue by tanzl** [Forgus/api-generator#19]
是我一个人有这个问题还是？

**Comment by superleeyom** [comment]
确实有这个问题，我修改了下，你重新安装下：[api-generator.zip](https://github.com/superleeyom/api-generator/releases/download/v1.0/api-generator.zip)

**Comment by Forgus** [comment]
api-generator的另一个作用是反向规范工程代码，目前的解析逻辑确实是不支持Controller注解里带value值的，建议去掉。另外，可以告诉我对Controller设值的理由么？

**Comment by superleeyom** [comment]
赞同@Forgus 说的，为了规范工程代码，建议修改直接去掉value，修改controller的名字即可

**Comment by tanzl** [comment]
> api-generator的另一个作用是反向规范工程代码，目前的解析逻辑确实是不支持Controller注解里带value值的，建议去掉。另外，可以告诉我对Controller设值的理由么？

我用工具生成的自动加上了，确实没必要。
