### ISSUE TITLE
生成的doc文档出现乱码

### ISSUE THREAD

**Issue by yangxy81118** [Forgus/api-generator#25]
系统 win10
插件版本 2020.09.10 
IDEA 版本 2020.1.2 Ultimate

出现类似这样的乱码
## ²ÎÊýËµÃ÷
Ãû³Æ|ÀàÐÍ|±ØÌî|ÖµÓò·¶Î§|ÃèÊö/Ê¾Àý
---|---|---|---|---

**Comment by Forgus** [comment]
建议更新到最新版（v2020.02.18）再尝试
