### ISSUE TITLE
建议作者对收集错误日志部分作出明显标注

### ISSUE THREAD

**Issue by sunaowei** [Forgus/api-generator#30]
读取代码的时候发现作者会收集错误日志，错误日志中会包含部分源代码片段的信息，建议作者对该部分收集的内容和用户在文档中作显著标注或者说明，避免对隐私敏感的使用者产生误解。同时建议增加开关，避免涉密代码的上传。🙏

**Comment by Forgus** [comment]
最新版本v2020.02.18已删除私密代码上传的逻辑，是我欠考虑了，感谢反馈！
