### ISSUE TITLE
非常好用的插件，但是对于无接口的API支持问题

### ISSUE THREAD

**Issue by zxt47** [Forgus/api-generator#5]
您好，我试验了一下插件，很好用，但是对于一些非接口形式的API，例如单纯的POJO，但是会有一些复杂的方法，就不支持展示了，而是当作一个普通的POJO，可否支持一下这种呢？

**Comment by Forgus** [comment]
这个插件的初衷是高效维护API文档。主要是REST API，因为HTTP接口实现了语言无关性，所以需要辅以文档来加以说明。当然出于某些团队内部约定要对dubbo接口要进行评审，也需要将相关接口转成文档的形式以便于阅读，所以该插件也支持了普通Java接口的文档生成，POJO文档主要用于描述MQ消息体字段。至于你说的要将普通方法转成文档，我想应该没有必要，直接看代码更直观

**Comment by zxt47** [comment]
好的，刚刚看到，谢谢解答
