### ISSUE TITLE
插件支持 IDEA 社区版么

### ISSUE THREAD

**Issue by dinghongfei** [Forgus/api-generator#6]
您好，我现在的项目是springboot项目，IDEA是社区版，执行生成操作的时候，报 Invalid Class File!。
这个是因为 IDEA社区版的问题么？

**Comment by Forgus** [comment]
支持社区版的，你可以把相关的代码以及详细错误信息截图出来我看下

**Comment by dinghongfei** [comment]
你好，可能是电脑原因，同一个版本的IDEA，同一套代码，在win10上，upload失败，在win7上可以成功。
